version: '2'

services:
  db:
    image: postgres:9.6.2-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: ./back
    command: bundle exec puma --config config/puma.rb
    environment:
    - RAILS_ENV=development
    - PORT=3000
    - GITHUB_KEY
    - GITHUB_SECRET
    - API_URL
    volumes:
    - ./back:/app
    - bundle_install:/app/vendor/bundle
    - bundle:/app/.bundle
    ports:
    - 3000:3000
    depends_on:
    - api
    - db
  api:
    build: 
      context: ./api
    command: go run Main.go
    volumes:
      - ./api:/echo-server
    ports:
      - 1323:1323

volumes:
  postgres_data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
