version: '2'

services:
  db:
    image: postgres:9.6.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: 
      context: ./api
    command: gin -a 1323 -p 4000
    volumes:
      - ./api:/echo-server
    ports:
      - 1323:4000
  web:
    build:
      context: ./back
    command: bundle exec puma --config config/puma.rb
    environment:
      - RAILS_ENV=development
      - PORT=3000
      - GITHUB_KEY
      - GITHUB_SECRET
      - API_URL
    volumes:
      - ./back:/app
      - bundle_install:/app/vendor/bundle
      - bundle:/app/.bundle
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    links: 
      - api
      - db

volumes:
  postgres_data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
